version: "3.9"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: "celery -A core.worker.celery worker --loglevel=info -f celery.log --concurrency=1"
    volumes:
      - worker_data:/usr/src/app
    env_file:
      - .env
    depends_on:
      - redis
      - quiz
    container_name: worker

  quiz:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    container_name: quiz


volumes:
  postgres_data:
  worker_data:
